### PR TITLE
release: bump version to 1.1.0

### PR DESCRIPTION
**Pull request by radoering**
### Added

- Add support for exporting `constraints.txt` files ([#128](https://github.com/python-poetry/poetry-plugin-export/pull/128)).

### Fixed

- Fix an issue where a relative path passed via `-o` was not ìnterpreted relative to the current working directory ([#130](https://github.com/python-poetry/poetry-plugin-export/pull/130)).
- Fix an issue where the names of extras were not normalized according to PEP 685 ([#123](https://github.com/python-poetry/poetry-plugin-export/pull/123)).

### CODE REVIEW

**Review by neersighted — CHANGES_REQUESTED** [review]
I'd like to block 1.1 on #121 if we can get it finished this weekend.

**Comment by dimbleby** [comment]
> ... #121 if we can get it finished this weekend

probably depends on whether you're willing to overlook, or rectify, the missing testcase ...

**Comment by neersighted** [comment]
> probably depends on whether you're willing to overlook, or rectify, the missing testcase ...

The intention is to write the test case, yes. I likely will just implement it myself in a successor as the existing PR is not quite correct and the contributor is stuck on writing tests.

**Comment by radoering** [comment]
The weekend is over so let's go on. We shouldn't delay poetry 1.2.2 and thereby eventually poetry 1.3.0 because of this. By the way, #121 seems like a simple bugfix that can go in a patch release at any time and should not block this release.

**Comment by neersighted** [comment]
Go ahead and do it -- I haven't started on rewriting that PR, though it is still quite trivial to fix, I just need to find time.

**Review by neersighted — CHANGES_REQUESTED** [review]
Looks like we should bump our Poetry-core dep to 1.2.x -- otherwise, LGTM.

**Review by Secrus — APPROVED** [review]

**Comment by radoering** [comment]
> Looks like we should bump our Poetry-core dep to 1.2.x -- otherwise, LGTM.

IMO that's not necessary because it still works with poetry-core 1.1.x. Bumping poetry-core effectively means bumping poetry to 1.2.1. We'll do a bump after the next release of poetry/poetry-core anyway to fix some typing issues.

**Comment by neersighted** [comment]
Fair enough!

**Review by neersighted — APPROVED** [review]

**Pull request merged**
