### PR TITLE
Use resolved references for vcs dependencies

### LINKED ISSUE #35: `poetry export` uses branch name for VCS dependencies rather than resolved commit hash
<!--
  Hi there! Thank you for discovering and submitting an issue.

  Before you submit this; let's make sure of a few things.
  Please make sure the following boxes are ticked if they are correct.
  If not, please try and fulfill these first.
-->

<!-- Checked checkbox should look like this: [x] -->
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

<!--
  Once those are done, if you're able to fill in the following list with your information,
  it'd be very helpful to whoever handles the issue.
-->

- **OS version and name**: Debian 10
- **Poetry version**: 1.1.7 (also reproducible with 1.2.0a1)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/0xallie/072e72cbf1f002f48944d0f93585e4ae

## Issue
Given the above `pyproject.toml` file, `poetry export --without-hashes -o requirements.txt` will generate the following output:

```
backports.functools-lru-cache==1.6.4; python_version >= "2.6" and python_version < "3"
beautifulsoup4==4.9.3
cssutils==1.0.2
enum34==1.1.10; python_version < "3.4"
future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0"
lxml==4.4.0
pycaption @ git+https://github.com/pbs/pycaption@master
six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0"
soupsieve==1.9.6
```

Relevant section of `poetry.lock`:

```
[[package]]                                                                                                                                                       
name = "pycaption"                                                                                                                                                
version = "1.0.6"                                                                                                                                                 
description = ""                                                                                                                                                  
category = "main"                                                                                                                                                 
optional = false                                                                                                                                                  python-versions = "*"                                                            
develop = false                                                                                                                                                   
                                                                                                                                                                  
[package.dependencies]                                                                                                                                            
beautifulsoup4 = ">=4.8.1,<4.10"                                                                                                                                  
cssutils = ">=0.9.10"                                                                                                                                             enum34 = {version = "*", markers = "python_version < \"3.4\""}
future = "*"                                                                                                                                                      
lxml = ">=3.2.3"                                                                                                                                                  
six = ">=1.9.0"                                                                                                                                                   
                                                                                                                                                                  
[package.source]                                                                                                                                                  
type = "git"
url = "https://github.com/pbs/pycaption" 
reference = "master"
resolved_reference = "3f377a32eb04a0ef79548d8f595092e249499bb4"             
```

Based on this, I would expect `requirements.txt` to contain the following:

```
pycaption @ git+https://github.com/pbs/pycaption@3f377a32eb04a0ef79548d8f595092e249499bb4
```

### PR DESCRIPTION
**Pull request by koffie**
Fixes #35

### CODE REVIEW

**Comment by koffie** [comment]
once there is a releasy of poetry-core that includes the changes of 1.7.0.dev0 the pyproject.toml should be updated to use that release and this PR should be good to go.

**Comment by koffie** [comment]
After the release of poetry 1.6.0 which contains the necessary changes, this one is now ready for review.

**Comment by radoering** [comment]
Can you please relock with Poetry 1.6.1?

**Comment by koffie** [comment]
> Can you please relock with Poetry 1.6.1 (use Poetry 1.6.1 to create the lockfile)?

Done!

**Review by radoering — APPROVED** [review]

**Pull request merged**
