### PR TITLE
simplify handling of extras

### PR DESCRIPTION
**Pull request by dimbleby**
extras in this plug-in are never None, or True, or False: just a (possibly-empty) collection of strings

### CODE REVIEW

**Comment by neersighted** [comment]
I'd like to bring this in, but it's failing mypy -- PTAL.

**Comment by dimbleby** [comment]
poetry types are already changed upstream to match this, but until a new version is released, mypy will fail here

**Comment by neersighted** [comment]
Rebased on top of core 1.3.

**Comment by neersighted** [comment]
Wow, there's some fascinating failures happening -- back to you @dimbleby :laughing:

**Comment by dimbleby** [comment]
the reason for the failure is that in poetry 1.2.2 `get_extra_package_names()` returns an iterator, so the check that goes something like:
```python
extra_package_names = get_extra_package_names()
for package in packages:
   if package in extra_package_names:
     ...
```
consumes the iterator as it goes and you might or might not be lucky when checking the second and subsequent packages.

On master, `get_extra_package_names()` returns a set and there is no problem.

Could patch this now with an explicit `set()`, or could wait for poetry 1.3 to be released.  As usual, the circular dependency makes this more awkward than it ought to be...

**Comment by dimbleby** [comment]
rebased on #167 which I expect should allow the CI to pass

**Review by radoering — APPROVED** [review]

**Pull request merged**
